/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.twu;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void testAppHasAGreeting() {

    }
}
