/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.twu;

import com.twu.entity.Admin;
import com.twu.entity.User;

public class MainTest {

    User user = new User("yangqian");
    Admin admin = new Admin("admin", "password");


}
